// Generated by CoffeeScript 1.8.0
(function() {
  var coffee;

  coffee = require('coffee-script');

  module.exports = function(grunt) {
    grunt.initConfig({
      clean: {
        build: {
          src: ["lib", ".cache", "tests.js.map", "tests.js"]
        }
      },
      copy: {
        main: {
          files: [
            {
              expand: true,
              cwd: 'src/',
              src: ['**/*.js'],
              dest: 'lib/'
            }
          ]
        }
      },
      newer: {
        options: {
          cache: '.cache'
        }
      },
      coffee: {
        options: {
          sourceMap: true
        },
        all: {
          src: ['**/*.coffee.md', '**/*.coffee'],
          dest: 'lib',
          cwd: 'src',
          expand: true,
          ext: '.js'
        }
      },
      powerbuild: {
        options: {
          sourceMap: true,
          node: false,
          handlers: {
            '.coffee': function(src, canonicalName) {
              var js, v3SourceMap, _ref;
              _ref = coffee.compile(src, {
                sourceMap: true,
                bare: true
              }), js = _ref.js, v3SourceMap = _ref.v3SourceMap;
              return {
                code: js,
                map: v3SourceMap
              };
            }
          }
        }
      },
      watch: {
        options: {
          nospawn: true
        },
        all: {
          files: ['Gruntfile.coffee', 'tasks/*.coffee', 'src/**/*.coffee', 'src/**/*.coffee.md', 'src/**/*.nools', 'src/**/*.js', 'test/*.coffee']
        }
      }
    });
    grunt.loadNpmTasks('grunt-contrib-copy');
    grunt.loadNpmTasks('grunt-release');
    grunt.loadNpmTasks('grunt-contrib-watch');
    grunt.loadNpmTasks('grunt-contrib-coffee');
    grunt.loadNpmTasks('grunt-contrib-clean');
    grunt.loadNpmTasks('grunt-newer');
    grunt.loadNpmTasks('powerbuild');
    grunt.registerTask('build', ['newer:coffee', 'copy']);
    grunt.registerTask('rebuild', ['clean', 'build']);
    grunt.registerTask('watch', ['watch']);
    return grunt.registerTask('default', ['build']);
  };

}).call(this);
