// Generated by CoffeeScript 1.8.0
(function() {
  var EventEmitter, InterfacedObject, inherits, util;

  EventEmitter = require("events").EventEmitter;

  util = require("./util");

  inherits = util.inherits;

  module.exports = InterfacedObject = (function() {
    inherits(InterfacedObject, EventEmitter);

    function InterfacedObject() {
      this.RefCount = 0;
    }

    InterfacedObject.prototype.addRef = function() {
      return ++this.RefCount;
    };

    InterfacedObject.prototype.destroy = function() {
      return this.emit("destroy", this);
    };

    InterfacedObject.prototype.release = function() {
      var result;
      result = --this.RefCount;
      if (result < 0) {
        this.destroy();
      }
      return result;
    };

    InterfacedObject.prototype.free = InterfacedObject.prototype.release;

    return InterfacedObject;

  })();

}).call(this);
