// Generated by CoffeeScript 1.9.3
(function() {
  var LevelErrors, LevelUPError, RedirectError, RedirectExceedError, SubkeyError, createError, extend;

  extend = require("xtend");

  createError = require("errno").create;

  LevelErrors = require("levelup-sync/lib/errors");

  LevelUPError = LevelErrors.LevelUPError;

  SubkeyError = createError("LevelSubkeyError", LevelUPError);

  RedirectError = createError("RedirectError", SubkeyError);

  RedirectExceedError = createError("RedirectExceedError", RedirectError);

  RedirectError.prototype.redirect = true;

  RedirectError.prototype.status = 300;

  RedirectExceedError.prototype.redirectExceed = true;

  RedirectExceedError.prototype.status = 301;

  module.exports = extend(LevelErrors, {
    SubkeyError: SubkeyError,
    RedirectError: RedirectError,
    RedirectExceedError: RedirectExceedError
  });

}).call(this);
